name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Use pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Deploy story
      run: pnpm deploy:csv
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}